require:
  - rubocop-rails

Rails:
  Enabled: true

AllCops:
  # Rubyのバージョンを指定
  TargetRubyVersion: 2.5.5
  # 除外するファイル
  Exclude:
    - bin/*
    - db/**/*
    - config/**/*
    - Gemfile
    - Rakefile
    - spec/rails_helper.rb
    - spec/spec_helper.rb

# Missing magic comment # frozen_string_literal: true. を無視
Style/FrozenStringLiteralComment:
  Enabled: false

# Missing top-level class documentation comment. を無視
Style/Documentation:
  Enabled: false

# コメント行はチェックしない
Metrics/LineLength:
  IgnoredPatterns: ['(\A|\s)#']